### PR TITLE
Update `matplotlib.colors.Colormap`

### PR DESCRIPTION
**Pull request by stdedos**
* `Colormap` defines `N` as a parameter
* Define `Color` as `RGBColor | RGBAColor | str`

Additionally:
* Update `.gitignore` via https://github.com/github/gitignore/blob/e5323759e387ba347a9d50f8b0ddd16502eb71d4/Python.gitignore

Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>

### CODE REVIEW

**Comment by stdedos** [comment]
Sadly, the positive tests fail https://github.com/stdedos/matplotlib-stubs-hoel/actions/runs/6083645074, and I am not sure how to tackle them.

https://app.element.io/#/room/#python_typing:gitter.im is also empty 😢 

-----

However, formally the first 3 commits should be a step forward if @hoel-bagard you'd consider them

**Comment by hoel-bagard** [comment]
@stdedos The first three commits look good to me, however the test would need to be fixed before merging. I'll see if I can help on that front in the next few days. 

Also, I don't think `npt.NDArray[RGBAColor]`  is a valid type. It would be interesting to be able to check that through the tests.

**Comment by stdedos** [comment]
I'll split that (and some GH-actions testing) on a separate PR

**Comment by stdedos** [comment]
Um ... you merged, but you are reverting? 😕

**Comment by hoel-bagard** [comment]
Am I reverting somewhere ?
I just thought (too late) that I probably should have squashed merged.

**Comment by stdedos** [comment]
I fetched upstream, and there's a revert-branch - and I got scared 😝 

I may be glad you didn't. Those 3 changes independent of each other 😄

**Pull request merged**
